name: Hellow World
on: [push] #событие 
jobs: #работы
  hello-linux: #название работы
    runs-on: ubuntu-latest #OS
    steps: #шаги
      - name: Hello  #название шага
        run: echo "Hellow World" #действия
      - name: Install the dependences
        run: pip3 install pyinstaller      
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Tests
        run: python3 test.py      
      - name: Build the executable
        run: pyinstaller --windowed --onefile gui.py
      - name: Upload gui-linux
        uses: actions/upload-artifact@v2
        with:
          name: gui-linux
          path: dist/gui
          
  hello-windows: #название работы
    runs-on: windows-latest #OS
    steps: #шаги
      - name: Hello  #название шага
        run: echo "Hellow World" #действия
      - name: Install the dependences
        run: pip3 install pyinstaller      
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Tests
        run: python3 test.py      
      - name: Build the executable
        run: pyinstaller --windowed --onefile gui.py
      - name: Upload gui-windows
        uses: actions/upload-artifact@v2
        with:
          name: gui-windows
          path: dist/gui.exe
          
        
                
        